server:
  port: 8080

spring:
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    jedis:
      pool:
        max-idle: 20
        min-idle: 1
        max-active: 8
        max-wait: 60000
    database: 0



